# Generated by Django 5.2.8 on 2026-04-24 22:23

from django.db import migrations, models


def cargar_cargos_desde_empleados(apps, schema_editor):
    Cargo = apps.get_model('core', 'Cargo')
    Empleado = apps.get_model('core', 'Empleado')

    cargos_existentes = (
        Empleado.objects.exclude(cargo__isnull=True)
        .exclude(cargo__exact='')
        .values_list('cargo', flat=True)
        .distinct()
    )

    for nombre_cargo in cargos_existentes:
        nombre_cargo = (nombre_cargo or '').strip()
        if nombre_cargo:
            Cargo.objects.get_or_create(nombre=nombre_cargo)


def revertir_carga_cargos(apps, schema_editor):
    Cargo = apps.get_model('core', 'Cargo')
    Cargo.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nombre'],
            },
        ),
        migrations.RunPython(cargar_cargos_desde_empleados, revertir_carga_cargos),
    ]
