# Generated by Django 5.2.8 on 2026-04-24 22:30

from django.db import migrations, models


def backfill_sueldo_desde_nomina(apps, schema_editor):
    Empleado = apps.get_model('core', 'Empleado')
    Nomina = apps.get_model('core', 'Nomina')

    for empleado in Empleado.objects.all():
        ultima_nomina = (
            Nomina.objects.filter(empleado_id=empleado.id)
            .order_by('-fecha_pago', '-id')
            .first()
        )
        if ultima_nomina and ultima_nomina.salario_base is not None:
            empleado.sueldo_mensual_dop = ultima_nomina.salario_base
            empleado.save(update_fields=['sueldo_mensual_dop'])


def revert_backfill_sueldo(apps, schema_editor):
    Empleado = apps.get_model('core', 'Empleado')
    Empleado.objects.update(sueldo_mensual_dop=0)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sueldo_mensual_dop',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RunPython(backfill_sueldo_desde_nomina, revert_backfill_sueldo),
    ]
